apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prober
rules:
  - apiGroups: ["", "apps"]
    # "" indicates the core API group
    resources: [ "deployments", "namespaces", "probes" ]
    verbs: [ "get", "list", "update", "patch" ]
