apiVersion: apps/v1
kind: Deployment
metadata:
  name: prober
  labels:
    app: prober
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prober
  template:
    metadata:
      labels:
        app: prober
    spec:
      serviceAccountName: prober
      containers:
        - name: prober
          image: dines97/prober:latest
          
