apiVersion: dteknoloji.com/v1alpha1
kind: Probe
metadata:
  name: rabbitmq
  namespace: default
spec:
  type: RabbitMQ
  connectionString: 'amqp://localhost:19420'
  timeout: 1
  severity: critical
  description: 'Some description'
