apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "dteknoloji.com:probe:reader"
rules:
  - apiGroups: ["dteknoloji.com"]
    resources: ["probes"]
    verbs: ["get", "list", "watch"]
