apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prober
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prober
subjects:
  - kind: ServiceAccount
    name: prober
    namespace: default

