apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: probes.dteknoloji.com
spec:
  scope: Namespaced
  group: dteknoloji.com
  versions:
    - name: v1alpha1
      storage: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                connectionString:
                  type: string
                timeout:
                  type: integer
                severity:
                  type: string
                description:
                  type: string
  names:
    kind: Probe
    singular: probe
    plural: probes
    # shortNames:
    #   - pb

