name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    env: 
      BUILD_CONFIG: Release
      PROJECTS_PATH: ./Projects/AspNetCoreHealthChecker/
    strategy: 
      matrix:
        project_name: ["AspNetCoreHealthChecker.RabbitMQ"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore $PROJECTS_PATH${{ matrix.project_name }}/${{ matrix.project_name }}.csproj
      - name: Build
        run: dotnet build --no-restore -c $BUILD_CONFIG -o $PROJECTS_PATH${{ matrix.project_name }}/${{ matrix.project_name }}.csproj
      - name: Pack
        run: dotnet pack --no-restore --no-build -c $BUILD_CONFIG  -o ./artifactsx $PROJECTS_PATH${{ matrix.project_name }}/${{ matrix.project_name }}.csproj
      - name: Nuget publish
        run: dotnet nuget push ./artifacts/${{ matrix.project_name }}.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        
      # - name: Test
      #   run: dotnet test --no-restore --no-build --verbosity normal